### ISSUE TITLE
Upgrading to v0.3.2 results in `PhantomJS not found.`

### ISSUE THREAD

**Issue by uglymunky** [busterjs/grunt-buster#33] opened 2015-11-04 23:20 UTC
I noticed these changes in the changelist which make me think this is expected but I'm not sure what I should do:

```
* Use resolve-bin to find buster and phantomjs executables
* Add buster as a peer dependency
```

**Comment by dominykas** [comment] 2015-11-05 11:33
Duplicate of https://github.com/busterjs/grunt-buster/issues/31

**Closed** 2015-11-10 19:27 UTC

**Comment by dominykas** [comment] 2015-11-10 19:34
Published as 0.4
